### ISSUE TITLE
which model is the best

### ISSUE THREAD

**Issue by sunmengnan** [russoale/hmr2.0#15]
There are 8 models you provided , which one behaviors the best?

**Comment by russoale** [comment]
Hi @sunmengnan ,

these are the results:

![Screenshot 2021-10-22 at 11 53 13](https://user-images.githubusercontent.com/15835919/138434219-6fae4fa5-ebcc-4d5c-9ce2-7cb7a7700bf5.png)

**Comment by russoale** [comment]
@ChristianIngwersen
