### ISSUE TITLE
the demension error [1,112,112,64] and [1,115,115,64]

### ISSUE THREAD

**Issue by Mirandl** [russoale/hmr2.0#16]
Hi,
After I made up the environment, there is a ValueError: Dimension 1 in both shapes must be equal, but are 112 and 115. Shapes are [1,112,112,64] and [1,115,115,64]. I don't know what makes that and how could I do with it. Thank you !

**Comment by Songye-CUI** [comment]
Hi, I am having the same issue when running demo.py with a default image. I am wondering if you have found a solution yet. Thanks.

**Comment by khadijakhaldi** [comment]
I'm having the same error, please did you solve it?
