### ISSUE TITLE
Human3.6m  miss  CSV file 

### ISSUE THREAD

**Issue by Liuxiang0358** [russoale/hmr2.0#20]
Thank you for your excellent work. When I generated the Human3.6m data into a TFrecord file, I found that a CSV file was missing. Are you processing the data?
![微信截图_20220414174326](https://user-images.githubusercontent.com/42142386/163359164-554e4352-4b88-4d47-9967-2d48a372b9c9.png)

**Comment by russoale** [comment]
Hi @Liuxiang0358 ,

as mentioned in the [Readme](https://github.com/russoale/hmr2.0/tree/master/datasets_preprocessing#generate-tf-records) the Human 3.6M and Total Capture datasets were available in a proprietary format provided by my university.
I do not have access to these datasets anymore. Sorry
