### ISSUE TITLE
RuntimeError: restore did not succeed, pleas check if you set config.LOG_DIR correctly

### ISSUE THREAD

**Issue by HamzaKhalloufi** [russoale/hmr2.0#6]
**When I run the demo.py using the command line:** 
>python demo.py --image=lsp1.png --model=base_model --setting=paired\(joints\) --joint_type=cocoplus --init_toes=true, 
**I get the following issue:**

Saving logs to /content/hmr2.0/logs/paired(joints)/base_model

Configurations:
BATCH_SIZE                     1
CUSTOM_REGRESSOR_IDX           {0: 'regressor_toes_right.npy', 7: 'regressor_toes_left.npy'}
CUSTOM_REGRESSOR_PATH          /content/hmr2.0/models/regressors
DATASETS                       ['lsp', 'lsp_ext', 'mpii', 'coco', 'mpii_3d', 'h36m', 'total_cap']
DATA_DIR                       /data/ssd1/russales/tfrecords
DISCRIMINATOR_LEARNING_RATE    0.0001
DISCRIMINATOR_LOSS_WEIGHT      1
DISCRIMINATOR_WEIGHT_DECAY     0.0001
DS_KP2D                        {'lsp': 14, 'cocoplus': 19, 'custom': 21}
DS_KP3D                        {'lsp': 14, 'cocoplus': 14, 'custom': 16}
ENCODER_INPUT_SHAPE            (224, 224, 3)
ENCODER_ONLY                   True
EPOCHS                         55
GENERATOR_2D_LOSS_WEIGHT       60.0
GENERATOR_3D_LOSS_WEIGHT       60.0
GENERATOR_LEARNING_RATE        1e-05
GENERATOR_WEIGHT_DECAY         0.0001
INITIALIZE_CUSTOM_REGRESSOR    True
ITERATIONS                     3
JOINT_TYPE                     cocoplus
LOG_DIR                        /content/hmr2.0/logs/paired(joints)/base_model
NUM_CAMERA_PARAMS              3
NUM_JOINTS                     23
NUM_JOINTS_GLOBAL              24
NUM_KP2D                       19
NUM_KP3D                       14
NUM_PARALLEL                   16
NUM_POSE_PARAMS                72
NUM_SHAPE_PARAMS               10
NUM_SMPL_PARAMS                85
NUM_TEST_SAMPLES               186873
NUM_TRAINING_SAMPLES           678442
NUM_TRAIN_SMPL_SAMPLES         4116233
NUM_VALIDATION_SAMPLES         11463
NUM_VERTICES                   6890
RESTORE_EPOCH                  None
RESTORE_PATH                   None
ROOT_DATA_DIR                  /data/ssd1/russales
ROOT_PROJECT_DIR               /content/hmr2.0
SCALE_MAX                      1.23
SCALE_MIN                      0.8
SEED                           42
SMPL_DATASETS                  ['cmu', 'joint_lim']
SMPL_DATA_DIR                  /data/ssd1/russales/tfrecords/smpl
SMPL_MEAN_THETA_PATH           /content/hmr2.0/models/neutral_smpl_mean_params.h5
SMPL_MODEL_PATH                /content/hmr2.0/models/neutral_smpl_coco_regressor.pkl
TRANS_MAX                      20
USE_3D                         True
_Config__initialized           True
_Config__instance              <__main__.DemoConfig object at 0x7fc675d61cc0>

building model...

Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    result = model.detect(input_img)
  File "/content/hmr2.0/src/main/model.py", line 461, in detect
    raise RuntimeError('restore did not succeed, pleas check if you set config.LOG_DIR correctly')
RuntimeError: restore did not succeed, pleas check if you set config.LOG_DIR correctly

**Could you please help me to correct it!**

**Comment by AdRever** [comment]
I suggest that you review the path to the folder in which the model is located  inside your logs folder. By default the command points to the folder 'base_model' for. 
For example if you have not changed the name of the pretrained model  and it you are testing with paired setting, the model should be at this location 'base_model.paired/base_model' 
Hope it helps!

**Comment by HamzaKhalloufi** [comment]
**Thank you. You are right I corrected this issue but now I get this error. Have you any idea?**
building model...

Downloading data from https://github.com/keras-team/keras-applications/releases/download/resnet/resnet50v2_weights_tf_dim_ordering_tf_kernels_notop.h5
94674944/94668760 [==============================] - 1s 0us/step
Checkpoint restored from /content/hmr2.0/logs/paired(joints)/base_model/ckpt-56
WARNING:tensorflow:Layer generator is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

Traceback (most recent call last):
  File "/content/hmr2.0/src/visualise/demo.py", line 64, in <module>
    visualize(renderer, original_img, params, vertices, cam, joints)
  File "/content/hmr2.0/src/visualise/vis_util.py", line 174, in visualize
    img_overlay = renderer(vert_shifted, img=img, bg_color=np.array((255.0, 255.0, 255.0, 1)))
  File "/content/hmr2.0/src/visualise/trimesh_renderer.py", line 38, in __call__
    image_bytes = scene.save_image(resolution=(w, h), background=bg_color, visible=True)
  File "/usr/local/lib/python3.6/dist-packages/trimesh/scene/scene.py", line 812, in save_image
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/trimesh/exceptions.py", line 48, in failed
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/trimesh/viewer/__init__.py", line 18, in <module>
    from .windowed import (SceneViewer,
  File "/usr/local/lib/python3.6/dist-packages/trimesh/viewer/windowed.py", line 15, in <module>
    import pyglet.gl as gl
  File "/usr/local/lib/python3.6/dist-packages/pyglet/gl/__init__.py", line 244, in <module>
    import pyglet.window
  File "/usr/local/lib/python3.6/dist-packages/pyglet/window/__init__.py", line 1880, in <module>
    gl._create_shadow_window()
  File "/usr/local/lib/python3.6/dist-packages/pyglet/gl/__init__.py", line 220, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/usr/local/lib/python3.6/dist-packages/pyglet/window/xlib/__init__.py", line 165, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyglet/window/__init__.py", line 570, in __init__
    display = pyglet.canvas.get_display()
  File "/usr/local/lib/python3.6/dist-packages/pyglet/canvas/__init__.py", line 94, in get_display
    return Display()
  File "/usr/local/lib/python3.6/dist-packages/pyglet/canvas/xlib.py", line 123, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"

**Comment by AdRever** [comment]
Try to upgrade your python version to maybe 3.7 And see what happens

**Comment by mphirke** [comment]
Looking at your path, "/content/hmr2.0/src/visualise/demo.py" I assume you are using a cloud computing service (probably Colab, just from the path).

Because those don't have displays, pyglet/pygame gives you the NoDisplay error. 
You can still use hmr/hmr2.0 on cloud--you just can't see the 3D rendering using the show_3d_pose function. You can try using the TrimeshRenderer on Colab though, because it doesn't need pyglet.

Check this Colab link for reference - https://colab.research.google.com/drive/1o8sCmbPY-CxL5k79em1lkuumrVD4Ea8F?usp=sharing

If you want pyglet, you can try this out: https://colab.research.google.com/drive/1tug_bpg8RwrFOI8C6Ed-zo0OgD3yfnWy . I personally haven't tried it but it does seem to use pyvirtualdisplay to simulate a display.

**Comment by HamzaKhalloufi** [comment]
> Looking at your path, "/content/hmr2.0/src/visualise/demo.py" I assume you are using a cloud computing service (probably Colab, just from the path).
> 
> Because those don't have displays, pyglet/pygame gives you the NoDisplay error.
> You can still use hmr/hmr2.0 on cloud--you just can't see the 3D rendering using the show_3d_pose function. You can try using the TrimeshRenderer on Colab though, because it doesn't need pyglet.
> 
> Check this Colab link for reference - https://colab.research.google.com/drive/1o8sCmbPY-CxL5k79em1lkuumrVD4Ea8F?usp=sharing
> 
> If you want pyglet, you can try this out: https://colab.research.google.com/drive/1tug_bpg8RwrFOI8C6Ed-zo0OgD3yfnWy . I personally haven't tried it but it does seem to use pyvirtualdisplay to simulate a display.
> 
> **EDIT:** I had some time so I did something basic in [ this notebook](https://colab.research.google.com/drive/11nrF3ZqEV0KAD3j6bS-O0jNwzG8B75RM?usp=sharing). Basically uses virtual display,then saves the image in the visualise function and then we can simply use matplotlib to read the saved image. Hope that helps.

Thank You very much. I think this what exactly I want.

**Comment by mphirke** [comment]
model.detect() returns the 3d keypoints in a dict. You can modify demo.py to get the 3d keypoints.
`    joints3d = np.squeeze(result['kp3d'].numpy())`

https://github.com/russoale/hmr2.0/blob/fca5c8cba93c2ca1d93630118efcc5ca8a4085c6/src/main/model.py#L474-L481

**Comment by HamzaKhalloufi** [comment]
> model.detect() returns the 3d keypoints in a dict. You can modify demo.py to get the 3d keypoints.
> ` joints3d = np.squeeze(result['kp3d'].numpy())`
> 
> https://github.com/russoale/hmr2.0/blob/fca5c8cba93c2ca1d93630118efcc5ca8a4085c6/src/main/model.py#L474-L481

Thank you

**Comment by seanwynwins** [comment]
> model.detect

Hi, thanks so much for your comments, they've really helped so far! I understand that "kp3d" gives the 3D coordinates - however, is there any specific identification for the kp3d coordinates? For example, does the first element correspond to the left eye position, second element to the right eye position, etc? 

Also, is "kp3d" the only attribute that gives information about the 3d space? What is the "vertices" element for?

**Comment by nono-zz** [comment]
> Looking at your path, "/content/hmr2.0/src/visualise/demo.py" I assume you are using a cloud computing service (probably Colab, just from the path).
> 
> Because those don't have displays, pyglet/pygame gives you the NoDisplay error. You can still use hmr/hmr2.0 on cloud--you just can't see the 3D rendering using the show_3d_pose function. You can try using the TrimeshRenderer on Colab though, because it doesn't need pyglet.
> 
> Check this Colab link for reference - https://colab.research.google.com/drive/1o8sCmbPY-CxL5k79em1lkuumrVD4Ea8F?usp=sharing
> 
> If you want pyglet, you can try this out: https://colab.research.google.com/drive/1tug_bpg8RwrFOI8C6Ed-zo0OgD3yfnWy . I personally haven't tried it but it does seem to use pyvirtualdisplay to simulate a display.
> 
> **EDIT:** I had some time so I did something basic in [ this notebook](https://colab.research.google.com/drive/11nrF3ZqEV0KAD3j6bS-O0jNwzG8B75RM?usp=sharing). Basically uses virtual display,then saves the image in the visualise function and then we can simply use matplotlib to read the saved image. Hope that helps.

Hi, thank your for your solution, it really help me a lot!

**Comment by STRUGGLE1999** [comment]
> I suggest that you review the path to the folder in which the model is located inside your logs folder. By default the command points to the folder 'base_model' for. For example if you have not changed the name of the pretrained model and it you are testing with paired setting, the model should be at this location 'base_model.paired/base_model' Hope it helps!

hello,can I ask you for help?I also encountered this problem when running this file.Please tell me how to solve it.Thank you very much.
