### ISSUE TITLE
Way to improve results

### ISSUE THREAD

**Issue by AdRever** [russoale/hmr2.0#7]
Hello @russoale ! First of all thank you for you work! I have tried  couple of time to test with some images and the results are not so great. How could I get optimal results with your models? 
This is an example of a result I got:
![Figure_1](https://user-images.githubusercontent.com/65495424/97239493-206c6100-17c2-11eb-9716-b192ec9579f5.png)

**Comment by russoale** [comment]
Hi @AdRever, 

ideally the image is cropped to 224x224 and the person displayed is centered.
