### ISSUE TITLE
The train loss and train dataset?

### ISSUE THREAD

**Issue by uestcjackey** [russoale/hmr2.0#8]
Hi, thanks for your effort to open this good job.
I'm try to train with a part dataset of all, only mpii-3dhp or coco，but I feel puzzled because the train loss is so strange，for generator's loss it has downtrend at first,and then raised up to very large，I checked the trainning data by your tools and found it's OK.I wonder if there is any trainning tricks for GANs? and if you have the trainning curve or trainning localhost? looking forward for your reply,thank you.

**Comment by uestcjackey** [comment]
@russoale Could you give any advice？thany you so much

**Comment by russoale** [comment]
I'm not sure if I understood it correctly. Are you training with mosh data as well ?

**Comment by uestcjackey** [comment]
> I'm not sure if I understood it correctly. Are you training with mosh data as well ?

yes,I do. Bcs of the strange loss,I tried to train only by encoder,though it's loss not becoming to Nan,but seems not to fit the data when used h36m with only 2d and 3d kpts as labels.

**Comment by russoale** [comment]
Training only the encoder won't do the job, also stated in the original paper. You need to trian the decoder as well, as it acts like a weak supervision for the SMPL parameters. Keep in mind that the encoder's output are SMPL parameters, not raw 2D/3D data. That is to train HMR successfully it is a crucial part to have some kind of SMPL ground truth data. 
Hope that will help you. Sorry for the late response

**Comment by uestcjackey** [comment]
got it，thanks so much
